### ISSUE TITLE
getting error "item[filter.key].indexOf is not a function" while filtering on columns containing numeric values

### ISSUE THREAD

**Issue by Kaggelpiep** [jdcalkins/ng2-data-table#14]
Hi, I'm trying to implement filtering on columns containing numerical values. However Im getting the error below as soon as I input filtering text in the textbox. Creating a dropdownlist instead of a textbox does not matter.

"item[filter.key].indexOf is not a function"

It does not matter when the data to be filtered is of data type number or string in the accompanying class instance. When I apply an empty string to the data to be filtered like below to convert the numerical value into a string

     this.dataFilter.forEach(item => {
            for (let x = 0; x < item.length; x++) {
                item[x].columnName = ""+item[x].columnName;
            }
        });

filtering works as expected.

**Comment by jdcalkins** [comment]
Hello, this package doesn't have column filtering builtin. The mfDefaultSorter 'by' input expects a string or function name, which is the argument used by the lodash function _.sortBy. Do you have an example that shows how you are setting up your datatable with this package?

**Comment by Kaggelpiep** [comment]
Hi, thanks for your response. Our solution now is to disable filtering on numerical columns unless it's absolutely necessary. We're setting up our datatable like below:

#import the package
import { DataTableModule } from "ng2-data-table/lib/DataTableModule";

#declare variables
tableData: Observable<tableItem[]>;
tableDataFilter: tableItem; 
selectedtableData: tableItem[] = [];

#set up the table in the .html file

    <table class="table table-striped" [mfData]="tableData | async" #mf="mfDataTable" (mfSelectedEntities)="setSelectedEntities($event)">
             <thead>
                 <tr>
                     <th style="width:10%">
                         <mfRowSelectorHead [mfTable]="mf"></mfRowSelectorHead>
                     </th>
                     <th style="width: 40%">
                         <mfDefaultSorter by="sequence">sequence</mfDefaultSorter><br />
                         <input type="text" id="sequenceFilter" [(ngModel)]="tableDataFilter.sequence" />
                     </th>
                 </tr>
             </thead>
             <tbody>
                 <tr *ngFor="let tableData of mf.data | moFilter : tableDataFilter" [class.selected]="selectedtableData?.indexOf(tableData) > -1">
                     <td><mfRowSelector [entity]="tableData" [checkboxId]="tableData.productCode" (selectEntity)="mf.addRemoveSelectedEntity($event)"></mfRowSelector></td>
                     <td>{{tableData.sequence}}</td>
                 </tr>
             </tbody>
         </table>

**Comment by Kaggelpiep** [comment]
Follow-up: I was under the impression that sorting was part of the ng2-data-table package. It turned out to be custom code which contained an error. Therefore this issue is non-existent and can be closed.
