### ISSUE TITLE
DataTableModule is not an NgModule

### ISSUE THREAD

**Issue by itsnotvalid** [jdcalkins/ng2-data-table#15]
angular version: 2.4.3
anuglar-cli version: 1.0.0-beta25.5

I just started a new project to try things with angular2, but apparently I run into bugs of some components keeping to remind me that it doesn't fit together. Now what it gives to me is that this module is not written in the format required by angular 2.4.3.

**Comment by jdcalkins** [comment]
#https://github.com/angular/angular-cli/issues/3426

It appears there may be an issue with angular-cli. I'll have to take a closer look at the ng2-data-table package to make sure it's AOT compliant. #19

**Comment by jdcalkins** [comment]
Resolved with package release v1.0.0

**Comment by ericalbers** [comment]
This is NOT closed.

**Comment by JonesCola** [comment]
I am also having this issue. It works fine until I try to install anything build targeting angular 2 (I think). My work around was to install then run "npm install". then I run "ng build -w". it throws the error but if I hit space in any of my code files and save then it works just fine. I dont know if that helps anyone else...
