### ISSUE TITLE
Export ng2-datatable to Excel,pdf,word

### ISSUE THREAD

**Issue by karthigamahe** [jdcalkins/ng2-data-table#17]
I m using  ng2-Datatable its really great in performance but i need to export the data table to excel and pdf format i try to find the code but its really tough..

Can anyone please  help me to do this functionality.....

**Comment by jdcalkins** [comment]
Hello,

You could probably write a serializer for the data to generate a .csv file that can be used with excel. As for the .pdf format, I have seen server-side html-to-pdf converters. You could save the html content of the datatable and send it back to your server for conversion. Then send the created pdf back to your client.
