### ISSUE TITLE
AoT support

### ISSUE THREAD

**Issue by vincent-cm** [jdcalkins/ng2-data-table#19]
AoT support

Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 8:14 in the original .ts file), resolving symbol DataTableDirectives in ~/projects//node_modules/ng2-data-table/datatable.d.ts

**Comment by jdcalkins** [comment]
The latest release v1.0.0 should resolve this.
